fix android builds: update hermes commit hash
android build fails with xcode 15 command line tools.

```
node_modules/react-native/sdks/hermes/lib/Support/Semaphore.cpp:35:3: error: use of undeclared identifier 'assert'
  assert(semPtr_ != nullptr && "sem_open should have succeeded");
  ^
1 error generated.
make[3]: *** [lib/Support/CMakeFiles/hermesSupport.dir/Semaphore.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [lib/Support/CMakeFiles/hermesSupport.dir/all] Error 2
make[1]: *** [tools/hermesc/CMakeFiles/hermesc.dir/rule] Error 2
make: *** [hermesc] Error 2
```

`#include <cassert>` is needed to bring assert implementation

See changes on our hermes fork
https://github.com/MetaMask/hermes/commit/52725e889185e53277e629f1f7043aa2913c97a9