fix: wallet connect QR code reading failure (#16684)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

Fix wallet connect QR code not reading bug. There are actually 2 bugs:
1. Error unrecognized QA code alert was introduced by the deeplinking PR
which throws an error when trying to parse the link. This is fixed by
reverting parseDeeplink file in this PR.
2. The second error is users will be stuck on Connecting to MetaMask
when 1 is resolved. This is due to the new arch update. This bug is
resolved by updating @react-native-community/netinfo". FYI, this is the
error I received: ```Failed to connect
uri=wc:380932e12af445a621a8d8c8961676106023b5eb6a2f68484e2a1bed8eb0143d@2?relay-protocol=irn&symKey=6d4299120fe96bb5c6c6c154d85fb0f5aa4a444511b00e24713d279ee284b0a5&expiryTimestamp=1750878139
[TypeError: _nativeInterface.default.getCurrentState is not a function
(it is undefined)]```

Fixes: https://github.com/MetaMask/metamask-mobile/issues/16553 and
https://github.com/MetaMask/metamask-mobile/issues/12483

1. Go to
[link](https://app.bitrise.io/build/2e4397cf-c953-4105-a2bc-5bba0c976086?tab=artifacts)
to install dev build on Android release build for this PR
2. Get wallet connect QR code from
[link](wc:7b6179dec6bf1b60d81ccfbf5ff513180d92a1c7846dc8a16128bf2f91ae63d9@2?relay-protocol=irn&symKey=fb2e9be82357595970e329923b16e7317fb880f15b50640c9f39b80e15ec9e98&expiryTimestamp=1750812873)
and click on Connect Wallet button
3. Use MetaMask app to scan this QR code
4. Should see the pop up

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

Bug 1
![Screenshot 2025-06-25 at 2 30
59 PM](https://github.com/user-attachments/assets/f90e83e6-a80e-4ace-88d5-42347b137f56)

Bug 2
![WC
After](https://github.com/user-attachments/assets/67f5ec21-a469-4b7b-9255-38bd04ab07ca)

![WC after
fix](https://github.com/user-attachments/assets/bfd6f4a0-948a-4812-8620-1a5e9d85eb2c)

<!-- [screenshots/recordings] -->

- [x] I’ve followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile
Coding
Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

- [x] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.