Revert "Re-patch @babel/runtime"
This reverts commit 76cc6e7598b9f4cd0ed37f971b4117c16562c95a.

As this no longer resolves `TypeError: (0 , _getPrototypeOf2.default) is not a function`.