fix android builds: update hermes commit hash (#7781)
## **Description**

<!--
Write a short description of the changes included in this pull request,
also include relevant motivation and context. Have in mind the following
questions:
1. What is the reason for the change?
2. What is the improvement/solution?
-->

**Patch file update breaks GH diff. Line 92 is the only change made.**

```diff
-def hermesVersion = "ae2ac688c3faf868d2360a10a7791226ed5702fb"
+def hermesVersion = "52725e889185e53277e629f1f7043aa2913c97a9"
```

android build fails with xcode 15 command line tools.

```
node_modules/react-native/sdks/hermes/lib/Support/Semaphore.cpp:35:3: error: use of undeclared identifier 'assert'
  assert(semPtr_ != nullptr && "sem_open should have succeeded");
  ^
1 error generated.
make[3]: *** [lib/Support/CMakeFiles/hermesSupport.dir/Semaphore.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [lib/Support/CMakeFiles/hermesSupport.dir/all] Error 2
make[1]: *** [tools/hermesc/CMakeFiles/hermesc.dir/rule] Error 2
make: *** [hermesc] Error 2
```

`#include <cassert>` is needed to bring assert implementation

See changes on our hermes fork

https://github.com/MetaMask/hermes/commit/52725e889185e53277e629f1f7043aa2913c97a9


## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding
Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it
is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
- [ ] In case it's "ready for review", I've changed it from "draft" to
"non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.