feat: Auto-failover to Quicknode when Infura is down (#15077)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

<!--
Write a short description of the changes included in this pull request,
also include relevant motivation and context. Have in mind the following
questions:
1. What is the reason for the change?
2. What is the improvement/solution?
-->

When Infura goes down, we want to automatically and invisibly redirect
requests from Infura RPC endpoints to Quicknode endpoints.

Some context:

- There is not one central Quicknode RPC endpoint that all Infura
requests will be forwarded to; rather, each Infura-supported chain gets
its own Quicknode endpoint. All of the Infura RPC endpoints that
Quicknode currently supports are:
  - Ethereum Mainnet
  - Linea Mainnet
  - Arbitrum Mainnet
  - Avalanche
  - Optimism (OP) Mainnet
  - Polygon Mainnet
  - Base Mainnet
- These Quicknode endpoint URLs contain an API key, so to keep them
secret, we assume they are stored in environment variables.
- The failover behavior itself is already present in
`@metamask/network-controller`, where a new `failoverRpcUrls` property
has been added to the `RpcEndpoint` type.
- In a previous commit, we already upgraded
`@metamask/network-controller`, which also modified how requests are
generally made so that failed requests are automatically retried (and
retries are paused if there are too many consecutive failures).
- To save money, the Quicknode endpoints will usually stay offline. When
Infura goes down, we send a signal via Segment. By triggering a backend
service this will cause Quicknode to come online. This takes a bit of
time, so we need to account for this.
- We also want to be able to control the behavior via a feature flag.

Given this, this commit:

- Adds a migration to fill in `failoverRpcUrls` for all supported Infura
RPC endpoints in NetworkController state with Quicknode endpoints.
- Listens for when Infura is unavailable (fails too many times) and
creates a Segment event so that Quicknode can be automatically
activated.
- Configures NetworkController with a longer retry timeout for the block
tracker. While Infura is down but we are waiting for Quicknode to come
online, we don't want the failover logic to think that Quicknode is also
down. This lengthened timeout will allow us to wait longer.
- Adds some minimal UI to allow users to see that Infura endpoints have
a failover URL assigned. The failover URL field is non-editable.
- Listens for when the feature flag is turned on and off and calls
appropriate methods in NetworkController to enable or disable the
failover behavior. This also shows or hides the aforementioned UI.

## **Related issues**

Closes #14120.

## **Manual testing steps**

There are 7 environment variables that you need to have set in `.js.env`
before you begin. Please contact me in Slack and I will give them to
you.

Additionally, you will need to log in to LaunchDarkly, navigate to the
Mobile environment, navigate to the
`wallet-framework-rpc-failover-enabled` feature flag, click on `main -
dev`, and enable the feature flag.

### Testing the UI changes

1. Check out this branch locally.
2. Run `yarn setup` or `yarn setup:expo` and then run `yarn watch`.
3. Open the app locally (simulator or physical device).
4. Set up an account if necessary.
5. Tap the network switcher and click on "Edit" next to "Ethereum
Mainnet".
6. Next to "Infura", you should see a "Failover" tag, and under the "RPC
URL" field, you should see a new field "Failover RPC URL" which should
contain a truncated Quicknode URL.
7. Open the network switcher again.
8. Add "Avalanche C-Chain" (which is an Infura-supported "additional"
network).
9. Next to "Infura", you should see a "Failover" tag, and under the "RPC
URL" field, you should see a new field "Failover RPC URL" which should
contain a truncated Quicknode URL.
10. Open the network switcher again.
11. Tap "Add a custom network".
12. Add a new network, such as "Flare Mainnet":
https://chainlist.wtf/chain/14/. Type in a network name, add a new RPC
URL, then type in the chain ID and the symbol.
- Make sure to put the RPC URL first and then the RPC name, or else you
won't be able to save.
13. Try switching to the new network. You should not see any errors
doing so.
14. Click on the network switcher and edit Flare. You should not see a
tag next to the name of the network, and you should not see a "Failover
RPC URL" field beneath "RPC URL".
15. Open the browser and go to `docs.metamask.io`.
16. Tap the hamburger menu, go to "Wallet API", tap the menu again, go
to "JSON-RPC API", tap the menu again, and go to
`wallet_addEthereumChain`.
17. Click on "Connect MetaMask".
18. Scroll down and run the request (which should add Gnosis). Accept
the approval and wait for the network to be switched to.
19. Tap back on the wallet view and open the network switcher.
20. Go to edit Gnosis. You should not see a tag next to the name of the
network, and you should not see a "Failover RPC URL" field beneath "RPC
URL".

### Testing the failover logic

1. Log into the MetaMask Developer portal.
2. Click on "Infura RPC" in the sidebar.
3. Click on the "All Endpoints" tab if not already selected.
4. Uncheck a network. Let's go with Linea Mainnet. Click "Save Changes".
5. Check out this branch locally.
6. We need to lower the time that the RPC failover logic waits before
trying an unavailable endpoint. Open `Engine.ts` and add the following
lines:
    ``` diff
      getRpcServiceOptions: (rpcEndpointUrl) => {
        const maxRetries = 4;
        const commonOptions = {
          fetch: globalThis.fetch.bind(globalThis),
          btoa: globalThis.btoa.bind(globalThis),
        };

        if (getIsQuicknodeEndpointUrl(rpcEndpointUrl)) {
          return {
            ...commonOptions,
            policyOptions: {
              maxRetries,
// When we fail over to Quicknode, we expect it to be down at
// first while it is being automatically activated. If an endpoint
// is down, the failover logic enters a "cooldown period" of 30
// minutes. We'd really rather not enter that for Quicknode, so
              // keep retrying longer.
              maxConsecutiveFailures: (maxRetries + 1) * 14,
            },
          };
        }

        return {
          ...commonOptions,
          policyOptions: {
            maxRetries,
            // Ensure that the circuit does not break too quickly.
            maxConsecutiveFailures: (maxRetries + 1) * 7,
    +       circuitBreakDuration: 60 * SECONDS
          },
        };
      },
    ```
7. Run `yarn setup` or `yarn setup:expo`.
8. We need to add some logging. Open
`node_modules/@metamask/network-controller/dist/rpc-service/rpc-service.cjs`.
Look for `async function _RpcService_executePolicy` and then make these
changes:
    ``` diff
async function _RpcService_executePolicy(jsonRpcRequest, fetchOptions) {
return await __classPrivateFieldGet(this, _RpcService_policy,
"f").execute(async () => {
+ console.log('<- Sending request to', this.endpointUrl.toString(),
'with', fetchOptions);
const response = await __classPrivateFieldGet(this, _RpcService_fetch,
"f").call(this, this.endpointUrl, fetchOptions);
              if (response.status === 405) {
                  throw rpc_errors_1.rpcErrors.methodNotFound();
              }
              if (response.status === 429) {
throw rpc_errors_1.rpcErrors.internal({ message: 'Request is being rate
limited.' });
              }
              if (response.status === 503 || response.status === 504) {
                  throw rpc_errors_1.rpcErrors.internal({
message: 'Gateway timeout. The request took too long to process. This
can happen when querying logs over too wide a block range.',
                  });
              }
              const text = await response.text();
+ console.log('-> Received response from', this.endpointUrl.toString(),
'body', text);
              if (jsonRpcRequest.method === 'eth_getBlockByNumber' &&
    ```
9. Run `yarn watch` or `yarn watch:clean`.
10. Open the app locally (simulator or physical device).
11. Set up an account if necessary.
12. Once you are on the home screen, tap on the network switcher and
choose Linea Mainnet.
13. In the terminal, you should start seeing lines like:
    ```
LOG <- Sending request to https://linea-mainnet.infura.io/v3/[REDACTED]
with {"body":
"{\"id\":6323405206068855,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}",
"headers": {"Accept": "application/json", "Content-Type":
"application/json"}, "method": "POST"}
LOG -> Received response from
https://linea-mainnet.infura.io/v3/<API_KEY> body project ID does not
have access to this network, see https://infura.io/dashboard
    ```
    as well as errors like:
    ```
ERROR [Error: PollingBlockTracker - encountered an error while
attempting to update
    latest block:
    Error: Could not parse response as it is not valid JSON
    ```
14. Wait about 2 minutes. After a while you should see:
    ```
LOG [MetaMask DEBUG]: Creating Segment event "RPC Service Unavailable"
with chain_id_caip: "eip155:59144", rpc_endpoint_url:
linea-mainnet.infura.io
    ```
    and then something like:
    ```
LOG <- Sending request to
https://compatible-late-dinghy.linea-mainnet.quiknode.pro/[REDACTED]/
with {"body":
"{\"id\":6323405206068857,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}",
"headers": {"Accept": "application/json", "Content-Type":
"application/json"}, "method": "POST"}
LOG -> Received response from
https://compatible-late-dinghy.linea-mainnet.quiknode.pro/[REDACTED]/
body {"jsonrpc":"2.0","id":6323405206068857,"result":"0x11beec8"}
    ```
15. Now switch back to the MetaMask Developer console and re-enable
Linea Mainnet.
16. Switch to Ethereum Mainnet and then back to Linea Mainnet.
17. You should now start seeing:
    ```
LOG <- Sending request to https://mainnet.infura.io/v3/[REDACTED] with
{"body":
"{\"id\":6323405206068859,\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[]}",
"headers": {"Accept": "application/json", "Content-Type":
"application/json"}, "method": "POST"}
    ```

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

Editing an Infura network:

<img width="488" alt="Screenshot 2025-05-13 at 1 42 25 PM"
src="https://github.com/user-attachments/assets/5df2e37b-303f-47f1-ae58-fb6825687a83"
/>

### **After**

Editing an Infura network:

![Screenshot 2025-05-02 at 8 58
41 AM](https://github.com/user-attachments/assets/47bfbf60-d83f-4b29-b683-f80bfd0318eb)

![Screenshot 2025-05-02 at 9 10
28 AM](https://github.com/user-attachments/assets/f82c1354-ae29-466d-9eba-9451aa7633c7)

Editing a custom network:

![Screenshot 2025-05-02 at 8 59
08 AM](https://github.com/user-attachments/assets/d9708c64-eef8-42ef-9c5b-3b2fb155829a)

Here is a video that goes through all Quicknode-suppported Infura
networks and then shows selecting a custom RPC endpoint vs. Infura RPC
endpoint:


https://github.com/user-attachments/assets/50fdddbb-2d88-4c7d-ac02-8e38371b2956

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile
Coding
Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.